### ISSUE TITLE
KeyboardInterrupt not working in Python 2.7

### ISSUE THREAD

**Issue by manjumanikumar** [atulsingh0/Python#1]
Hy Atul,

Is there any problem when user presses Ctrl-C the Python compiler fails to invoke the Keyboard Interrupt? Attached the same test file for your reference

[exception.txt](https://github.com/atulsingh0/Python/files/303100/exception.txt)

**Comment by atulsingh0** [comment]
Hi Manju, 
Its because of "EoFError"  which should be "E**O**FError"

**Comment by manjumanikumar** [comment]
Thanks Atul,
However even after correcting the EOF too which resolved the 'Ctrl-Z' issue, I seem to face some problems with 'Ctrl-C', the keyboard Interrupt. Attached screenshot for the reference. 

1.) When 'Ctrl-Z' is pressed - which is correct
![image](https://cloud.githubusercontent.com/assets/17817769/15900014/d5174890-2d6b-11e6-9a63-d47fdc15da76.png)

2) When 'Ctrl-C' is pressed - I think this is incorrect

![image](https://cloud.githubusercontent.com/assets/17817769/15899874/47ecafaa-2d6b-11e6-9629-9a370f5d84a3.png)

**Comment by atulsingh0** [comment]
use a exit() in KeyboardInterrupt, Its working for me after fixing this
